name: CI
on:
  push: { branches: [ main ] }
  pull_request: {branches: [ main ] }


jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/seanjennings960/battery-health-analytics/dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: hatch test
